# SCHASDB Queries

In [3]:
%run "../common.ipynb"

#PUT THE QUERY NUMBER BELOW
qn = '1'


fileName="http://www.smartconnectedhealth.org/aura/webroot/db.jsp?qn="+qn+"&type=html";
dfQN = LoadDataSet(fileName, columns=None, checkForDateTime=False);

displayDFs(dfQN, showStats=False, maxrows=len(dfQN))

In [30]:
#CODE FOR BUTTON USER INTERFACE
#response = urllib.request.urlopen('http://www.smartconnectedhealth.org/SCHAS/data/sql/SQL.txt')
#html = response.read().decode("utf-8")
#html  = html.split("\n#--------------------------------------------------------------------------\n")

#qns = []
#for i in range(len(html)):
#    qns.append(html[i].split('\n')[0])

#print(qns)
#response.close()

In [ ]:
#from IPython.html import widgets
#from IPython.display import display

#def func(btn):
#    qn = btn.description
    #print(qn)


#for k in range(len(qns)):
#    btn = widgets.Button(description=qns[k])
#    btn.on_click(func)
#    display(btn)